name: Package and upload

on:
  push:
    branches:
      - 'master'

jobs:
  feature_test:
    runs-on: ubuntu-latest
    env:
      TARGET_RUNTIME: rhel.7.2-x64
      LAMBDA_FOLDER: Lambda
      S3_BUCKET: stephen-teodori-doctor-who
      CONFIG: Release
      PACKAGE_FOLDER: Validators
      PACKAGE_NAME_TEMPLATE: Validators.*.nupkg
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      - name: Package Lambda
        run: dotnet publish "./${LAMBDA_FOLDER}/" -c ${CONFIG} -r $TARGET_RUNTIME --no-self-contained
        shell: bash
      - name: Publish Nuget to GitHub registry
        run: dotnet nuget push ./${PACKAGE_FOLDER}/bin/${CONFIG}/${PACKAGE_NAME_TEMPLATE} -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/stephenteodori/ --skip-duplicate --no-symbols true
        shell: bash
      - name: Zip lambda package
        run: zip -j "${LAMBDA_FOLDER}.zip" ./${LAMBDA_FOLDER}/bin/${CONFIG}/*/${TARGET_RUNTIME}/publish/*.*
        shell: bash
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload Lambda zip to S3 bucket
        run: aws s3 cp "${LAMBDA_FOLDER}.zip" s3://${S3_BUCKET}/
        shell: bash