name: Unit test the pull request

on: pull_request

jobs:
  test_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      - name: Test with dotnet
        run: dotnet test --configuration Debug
        shell: bash
